import os

BOT_TOKEN = os.environ["BOT_TOKEN"]
APPWRITE_ENDPOINT = os.environ["APPWRITE_ENDPOINT"]
APPWRITE_PROJECT_ID = os.environ["APPWRITE_PROJECT_ID"]
APPWRITE_DATABASE_ID = os.environ["APPWRITE_DATABASE_ID"]
APPWRITE_USERS_COLLECTION = os.environ["APPWRITE_USERS_COLLECTION"]
APPWRITE_ALERTS_COLLECTION = os.environ["APPWRITE_ALERTS_COLLECTION"]
APPWRITE_SUBSCRIPTIONS_COLLECTION = os.environ["APPWRITE_SUBSCRIPTIONS_COLLECTION"]
APPWRITE_REFERRALS_COLLECTION = os.environ["APPWRITE_REFERRALS_COLLECTION"]
APPWRITE_API_KEY = os.environ["APPWRITE_API_KEY"]
ADMIN_TELEGRAM_ID = int(os.environ["ADMIN_TELEGRAM_ID"])
